
{{- range $vCluster := .Values.vClusters }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: {{ .namespace }}
  name: {{ .name }}
  labels:
    department: development
    distro: k3s
    version: v1.21.4-k3s1
  annotations:
    argocd.argoproj.io/sync-wave: "99"
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: default
  source:
    repoURL: 'https://charts.loft.sh'
    targetRevision: 0.11.1
    helm:
      values: |-
        syncer:
          extraArgs:
            - --tls-san={{ .name }}.{{ .domain }}
            - --out-kube-config-server=https://{{ .name }}.{{ .domain }}
        rbac:
          clusterRole:
            create: true
          role:
            create: true
            extended: true
        vcluster:
          image: rancher/k3s:v1.21.4-k3s1
        ingress:
          enabled: true
          pathType: ImplementationSpecific
          apiVersion: networking.k8s.io/v1
          ingressClassName: "nginx"
          annotations:
            nginx.ingress.kubernetes.io/backend-protocol: HTTPS
            nginx.ingress.kubernetes.io/ssl-passthrough: "true"
            nginx.ingress.kubernetes.io/ssl-redirect: "true"
          host: {{ .name }}.{{ .domain }}
    chart: vcluster
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true

{{ printf "---" }}
{{- end }}
