apiVersion: v2
name: argo-cd
version: 1.0.0
dependencies:
  - name: ingress-nginx
    repository: https://kubernetes.github.io/ingress-nginx
    version: 4.2.3
  - name: argo-cd
    version: 5.4.0
    repository: https://argoproj.github.io/argo-helm
  - name: argocd-image-updater
    version: 0.8.0
    repository: https://argoproj.github.io/argo-helm
